# Dictionary mapping codes to signal names. Used to display error codes for test cases with errors.
error_codes = {
             1: 'SIGHUP',
             2: 'SIGINT',
             3: 'SIGQUIT',
             4: 'SIGILL',
             5: 'SIGTRAP',
             6: 'SIGABRT',
             7: 'SIGBUS',
             8: 'SIGFPE',
             9: 'SIGKILL',
             10: 'SIGUSR1',
             11: 'SIGSEGV',
             12: 'SIGUSR2',
             13: 'SIGPIPE',
             14: 'SIGALRM',
             15: 'SIGTERM',
             16: 'SIGSTKFLT',
             17: 'SIGCHLD',
             18: 'SIGCONT',
             19: 'SIGSTOP',
             20: 'SIGTSTP',
             21: 'SIGTTIN',
             22: 'SIGTTOU',
             23: 'SIGURG',
             24: 'SIGXCPU',
             25: 'SIGXFSZ',
             26: 'SIGVTALRM',
             27: 'SIGPROF',
             28: 'SIGWINCH',
             29: 'SIGIO',
             30: 'SIGPWR',
             31: 'SIGSYS',
             32: 'OLE',
             33: 'MLE',
             34: 'TLE',
             35: 'RTLE',
             36: 'RF',
             37: 'IE',
             38: 'RETNZ',
             39: 'TERM',
            }

# Dictionary mapping codes to error messages. Used to display error codes for test cases with errors.
error_msg = {
             1: 'SIGHUP',
             2: 'SIGINT',
             3: 'SIGQUIT',
             4: 'SIGILL',
             5: 'SIGTRAP',
             6: 'SIGABRT',
             7: 'SIGBUS',
             8: 'SIGFPE',
             9: 'SIGKILL',
             10: 'SIGUSR1',
             11: 'Segmentation fault. Possible reasons may be your code has segmentation fault\
                 or Memory limit exceeded or your program is producing more output than it is allowed.',
             12: 'SIGUSR2',
             13: 'SIGPIPE',
             14: 'SIGALRM',
             15: 'SIGTERM',
             16: 'SIGSTKFLT',
             17: 'SIGCHLD',
             18: 'SIGCONT',
             19: 'SIGSTOP',
             20: 'SIGTSTP',
             21: 'SIGTTIN',
             22: 'SIGTTOU',
             23: 'SIGURG',
             24: 'SIGXCPU',
             25: 'SIGXFSZ',
             26: 'SIGVTALRM',
             27: 'SIGPROF',
             28: 'SIGWINCH',
             29: 'SIGIO',
             30: 'SIGPWR',
             31: 'SIGSYS',
             32: 'Output limit exceeded',
             33: 'Memory limit exceeded',
             34: 'CPU time limit exceeded',
             35: 'Total time limit exceeded',
             36: 'RF',
             37: 'IE',
             38: 'RETNZ',
             39: 'TERM',
            }
